### ISSUE TITLE
Firefox unknow address

### ISSUE THREAD

**Issue by Novite5** [corollari/ankiTab#12]
After scoring the answer, Ankitab will jump to address:

> chrome-search://local-ntp/local-ntp.html

which cannot be recognized by Firefox.

Thank you for your work!

**Comment by Novite5** [comment]
No. I get the addon from Mozilla official store.

**Comment by Novite5** [comment]
`
19:00:46.294 Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
19:00:47.473 Error: Could not establish connection. Receiving end does not exist. Browser.js:3:1937
19:01:10.779
'NoneType' object has no attribute 'hide' ankiConnect.js:22:17
ankiConnectInvoke/</<
moz-extension://e22a492a-4b7b-4a3a-b37d-9e3e9cf39d8a/libs/ankiConnect.js:22:17
19:01:11.471 TypeError: docShell.failedChannel is null[Learn More] NetErrorChild.jsm:683:13
19:01:11.693 Error: Could not establish connection. Receiving end does not exist.
Browser.js:3:1937
19:02:06.404 NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface]
network-response-listener.js:73

​`
this is the error log in web console.

**Comment by corollari** [comment]
Just fixed it! :tada: 
Thanks for reporting it :)

**Comment by corollari** [comment]
Just published the updated extension, it should be available after the review passes (~a few hours).

**Comment by Novite5** [comment]
Great! It works.
Thank you very much!
