### ISSUE TITLE
End of support for Firefox's add-on repository (AMO)

### ISSUE THREAD

**Issue by corollari** [corollari/ankiTab#3]
Due to AMO reviewers' constant disabling of the extension on AMO (without reading the reviewer comments I left for them nor spending the time to properly understand the extension before outright banning it), unresponsiveness to my replies and extremely hard to meet requests (eg: rewrite all of ankiweb's js code) I've decided to pull the extension from AMO.
Right now the extension works properly on Firefox and I'll do my best to keep it like that, so if anybody is interested on using it, they can just install it following [these instructions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Alternative_distribution_options/Sideloading_add-ons#Using_Install_Add-on_From_File).

If enough people is interested in bringing it to AMO I might look into it in the future.

**Comment by bartbussmann** [comment]
I haven't been able to install it in Firefox. After I have build from source, and I select the firefox.zip when adding the add-on from file, I get the message: "This add-on could not be installed because it appears to be corrupted." Am I doing something wrong?

**Comment by corollari** [comment]
Sorry, the issue is on my side. Firefox forces signing of every extension and I haven't uploaded the signed extension package.

Edit: See my last comment at the end of this issue for a link to a signed package

**Comment by corollari** [comment]
Thanks! If you find any bug on Firefox please just open an issue or notify me and I'll get it fixed.

**Comment by corollari** [comment]
Given that I'll be rewriting a part of the extension, I'll use this opportunity to make the changes necessary and try to get AnkiTab on AMO again.

**Comment by iacutone** [comment]
@corollari I love AnkiTab. Can you share another signed package? [This](https://albert.sh/ankitab-0.3.3-an+fx-windows.xpi) link no longer works. Thanks!

**Comment by corollari** [comment]
Sure, on it.

**Comment by corollari** [comment]
The signed package: [ankitab-0.5.1.1-fx.zip](https://github.com/corollari/ankiTab/files/4712919/ankitab-0.5.1.1-fx.zip)

It took a while because the package needs to be approved by Mozilla.

Let me know if you run into any problems with it :+1:

**Comment by iacutone** [comment]
The new link works. Thank you so much!

**Comment by VidFerris** [comment]
Would be useful to direct the Firefox link on the readme to this link - had to dig through the issues pages to find this.

**Comment by corollari** [comment]
@VidFerris Thanks for the suggestion, I've applied it on 0643f53d00d0fe44cf51590e291ef256d283aaac
