### ISSUE TITLE
Not working for firefox currently

### ISSUE THREAD

**Issue by JanEbbing** [corollari/ankiTab#6]
Hey, I'm trying to use this for firefox as it looks like great work!
However, the xpi you provided in #3 does not work anymore (I suspect due to it using ankiwebs API instead of AnkiConnect) and when I build the current github version myself I cannot install it as an addon (I guess the previous unsigned error).

Would be awesome if you could upload a signed version or enable us to build one!

**Comment by demolpolis** [comment]
Mine stopped working until I signed into ankiweb.net and agreed to the new term and conditions.  Instantly fixed it. 

It was flashing a card, then showing the "Congratulations! All cards scheduled for today have been reviewed" screen.

Is this what is happening to you?

**Comment by JanEbbing** [comment]
Hi, sorry for not describing the actual problem in detail.
I also hadn't signed the new Terms, but did so while trying to solve the problem. When I open a new tab, it just asks me to sign into my ankiweb account forever. If I go to the actual ankiweb website and log in there and then open a new tab, it again asks me to log in.

**Comment by corollari** [comment]
I just received an answer to the appeal I sent a few weeks ago on AMO. It took several weeks to just send  a one-liner saying "NO". Anyway, I will re-upload the updated version to AMO later today. 
About the old extension not working properly, I'm surprised that it even works, as dae blocked the extension from accessing ankiweb (that's the reason why it was eventually migrated to ankiweb).

About building it yourself, Firefox only allows loading non-signed extensions temporarily. If you're interested in installing it permanently, you should register on AMO as an extensions developer and sign it.

**Comment by corollari** [comment]
Btw, sorry for not replying in two days, I only saw this issue after someone else told me about it. In case this ever happens again just send me an email at me@albert.sh

**Comment by demolpolis** [comment]
I don't know much about what is happening behind the scenes here... but it works for me and I am extremely grateful for it.  It's crazy that an allegedly more open source browser ends up being more restrictive than Chrome. /shrug.

**Comment by JanEbbing** [comment]
Thanks a lot! works like a charm now.
