### ISSUE TITLE
do not work with Yandex browser

### ISSUE THREAD

**Issue by tamdrashtri** [corollari/ankiTab#8]
I tried this with Yandex but it does not work. It shows this message:

<img width="394" alt="screen shot 2018-11-06 at 10 21 48 am" src="https://user-images.githubusercontent.com/33707686/48084953-ddb4b700-e1ad-11e8-97ed-273ace3bfb2b.png">

**Comment by corollari** [comment]
Try loading it from the `extension` folder (`/Users/mac/Downloads/ankiTab-master/extension` in your case)

**Comment by tamdrashtri** [comment]
Hi Corollari, I tried following your tip but it still does not work: 

<img width="402" alt="screen shot 2018-11-06 at 7 45 32 pm" src="https://user-images.githubusercontent.com/33707686/48109517-a6212b80-e1fc-11e8-8776-e60c50db11a9.png">

**Comment by corollari** [comment]
It seems that, as a design choice, the Opera developers have disabled the API used to modify the new tab page[1]. Given that Yandex uses Opera extension that functionality is blocked in Yandex too. 
I'm not sure if there is any way to actually get it working on Yandex if the main functionality of the extension is intentionally blocked.

[1] https://forums.opera.com/topic/20490/using-chrome_url_overrides-for-extension/6

**Comment by corollari** [comment]
Closing as there doesn't seem to be any solution to this issue and there hasn't been any new comments.
