### ISSUE TITLE
deck page when tab is closed

### ISSUE THREAD

**Issue by stappis** [corollari/ankiTab#9]
hello!
currently, when you close an ankitab (or when you decide to go to a site), the question will still be open on anki... it'll harm the "average answer time" statistic, right?
would't it be possible to make anki go back to the 'decks page' when you close an ankitab (or go to a site), or something like that?
(sorry for my bad english)

*the title is kinda dumb, it's not necessarily JUST when you close a tab: when you go to a site, too

**Comment by corollari** [comment]
The fix is live in the master branch now, I'll release the new version of the extension in a few days. If you want to use the new version meanwhile you can load in unpacked.
